scope({c0_Machine:4, c0_Requirements:13, c0_Service:5, c0_Task:1, c0_cpu:13, c0_machine:5, c0_total_free:1});
defaultScope(1);
intRange(-8, 7);

c0_Service = Abstract("c0_Service");
c0_Requirements = Abstract("c0_Requirements");
c0_Machine = Abstract("c0_Machine");
c0_Task = Abstract("c0_Task");
c0_Resources = Abstract("c0_Resources").extending(c0_Requirements);
c0_requirements = c0_Service.addChild("c0_requirements").withCard(1, 1).extending(c0_Requirements);
c0_machine = c0_Service.addChild("c0_machine").withCard(1, 1);
c0_cpu = c0_Requirements.addChild("c0_cpu").withCard(1, 1);
c0_services = c0_Machine.addChild("c0_services");
c0_isFree = c0_Machine.addChild("c0_isFree").withCard(0, 1);
c0_limits = c0_Machine.addChild("c0_limits").withCard(1, 1).extending(c0_Resources);
c0_utilization = c0_Machine.addChild("c0_utilization").withCard(1, 1).extending(c0_Resources);
c0_total_free = c0_Task.addChild("c0_total_free").withCard(1, 1);
c0_MyTask = Clafer("c0_MyTask").withCard(1, 1).extending(c0_Task);
c0_GoogleCA = c0_MyTask.addChild("c0_GoogleCA").withCard(1, 1).extending(c0_Machine);
c0_GoogleNY = c0_MyTask.addChild("c0_GoogleNY").withCard(1, 1).extending(c0_Machine);
c0_GoogleTX = c0_MyTask.addChild("c0_GoogleTX").withCard(1, 1).extending(c0_Machine);
c0_MailService = c0_MyTask.addChild("c0_MailService").withCard(1, 1).extending(c0_Service);
c0_SearchService = c0_MyTask.addChild("c0_SearchService").withCard(1, 1).extending(c0_Service);
c0_CalendarService = c0_MyTask.addChild("c0_CalendarService").withCard(1, 1).extending(c0_Service);
c0_DriveService = c0_MyTask.addChild("c0_DriveService").withCard(1, 1).extending(c0_Service);
c0_machine.refToUnique(c0_Machine);
c0_cpu.refTo(Int);
c0_services.refToUnique(c0_Service);
c0_total_free.refTo(Int);
c0_Service.addConstraint($in($this(), joinRef(join(joinRef(join($this(), c0_machine)), c0_services))));
c0_Machine.addConstraint(ifOnlyIf(some(join($this(), c0_isFree)), none(join($this(), c0_services))));
c0_services.addConstraint(equal(joinRef(join(joinRef($this()), c0_machine)), joinParent($this())));
c0_utilization.addConstraint(equal(joinRef(join($this(), c0_cpu)), sum(join(join(joinRef(join(joinParent($this()), c0_services)), c0_requirements), c0_cpu))));
c0_utilization.addConstraint(lessThan(joinRef(join($this(), c0_cpu)), joinRef(join(join(joinParent($this()), c0_limits), c0_cpu))));
c0_Task.addConstraint(equal(joinRef(join($this(), c0_total_free)), card(join(global(c0_Machine), c0_isFree))));
c0_GoogleCA.addConstraint(equal(joinRef(join(join($this(), c0_limits), c0_cpu)), constant(10)));
c0_GoogleNY.addConstraint(equal(joinRef(join(join($this(), c0_limits), c0_cpu)), constant(16)));
c0_GoogleTX.addConstraint(equal(joinRef(join(join($this(), c0_limits), c0_cpu)), constant(14)));
c0_MailService.addConstraint(equal(joinRef(join(join($this(), c0_requirements), c0_cpu)), constant(4)));
c0_SearchService.addConstraint(equal(joinRef(join(join($this(), c0_requirements), c0_cpu)), constant(3)));
c0_CalendarService.addConstraint(equal(joinRef(join(join($this(), c0_requirements), c0_cpu)), constant(1)));
c0_DriveService.addConstraint(equal(joinRef(join(join($this(), c0_requirements), c0_cpu)), constant(2)));
max(joinRef(join(global(c0_MyTask), c0_total_free)));
