scope({c0_Feature:18, c0_MobilePhone:1, c0_cost:18, c0_total_cost:1});
defaultScope(1);
intRange(-128, 127);

c0_Feature = Abstract("c0_Feature");
c0_MobilePhone = Abstract("c0_MobilePhone");
c0_cost = c0_Feature.addChild("c0_cost").withCard(1, 1);
c0_hardware = c0_MobilePhone.addChild("c0_hardware").withCard(1, 1).extending(c0_Feature);
c0_screen = c0_hardware.addChild("c0_screen").withCard(1, 1).extending(c0_Feature);
c0_material = c0_screen.addChild("c0_material").withCard(1, 1).withGroupCard(1, 1).extending(c0_Feature);
c0_oled = c0_material.addChild("c0_oled").withCard(0, 1).extending(c0_Feature);
c0_amoled = c0_material.addChild("c0_amoled").withCard(0, 1).extending(c0_Feature);
c0_lcd = c0_material.addChild("c0_lcd").withCard(0, 1).extending(c0_Feature);
c0_keyboard = c0_hardware.addChild("c0_keyboard").withCard(0, 1).extending(c0_Feature);
c0_keyboardLight = c0_keyboard.addChild("c0_keyboardLight").withCard(0, 1).extending(c0_Feature);
c0_cpu = c0_hardware.addChild("c0_cpu").withCard(1, 1).extending(c0_Feature);
c0_extra_cpu = c0_hardware.addChild("c0_extra_cpu").withCard(0, 1).extending(c0_Feature);
c0_WiFi = c0_hardware.addChild("c0_WiFi").withCard(0, 1).extending(c0_Feature);
c0_location = c0_hardware.addChild("c0_location").withCard(0, 1).withGroupCard(1).extending(c0_Feature);
c0_gps = c0_location.addChild("c0_gps").withCard(0, 1).extending(c0_Feature);
c0_WiFiTriangulation = c0_location.addChild("c0_WiFiTriangulation").withCard(0, 1).extending(c0_Feature);
c0_software = c0_MobilePhone.addChild("c0_software").withCard(1, 1).extending(c0_Feature);
c0_browser = c0_software.addChild("c0_browser").withCard(0, 1).extending(c0_Feature);
c0_mediaplayer = c0_software.addChild("c0_mediaplayer").withCard(0, 1).extending(c0_Feature);
c0_map = c0_software.addChild("c0_map").withCard(0, 1).extending(c0_Feature);
c0_total_cost = c0_MobilePhone.addChild("c0_total_cost").withCard(1, 1);
c0_aPhone = Clafer("c0_aPhone").withCard(1, 1).extending(c0_MobilePhone);
c0_cost.refTo(Int);
c0_total_cost.refTo(Int);
c0_cost.addConstraint(greaterThanEqual(joinRef($this()), constant(0)));
c0_MobilePhone.addConstraint(equal(joinRef(join($this(), c0_total_cost)), sum(join(global(c0_Feature), c0_cost))));
c0_hardware.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_screen.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_material.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_oled.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(4)));
c0_amoled.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(6)));
c0_lcd.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(3)));
c0_keyboard.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(3)));
c0_keyboard.addConstraint(none(join(join(join(joinParent($this()), c0_screen), c0_material), c0_amoled)));
c0_keyboardLight.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(1)));
c0_cpu.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(5)));
c0_extra_cpu.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(4)));
c0_WiFi.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(5)));
c0_location.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_gps.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(2)));
c0_WiFiTriangulation.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(1)));
c0_WiFiTriangulation.addConstraint(some(join(joinParent(joinParent($this())), c0_WiFi)));
c0_software.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_browser.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_browser.addConstraint(some(join(join(joinParent(joinParent($this())), c0_hardware), c0_WiFi)));
c0_mediaplayer.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(0)));
c0_mediaplayer.addConstraint(some(join(join(joinParent(joinParent($this())), c0_hardware), c0_extra_cpu)));
c0_map.addConstraint(equal(joinRef(join($this(), c0_cost)), constant(2)));
c0_map.addConstraint(some(join(join(join(joinParent(joinParent($this())), c0_hardware), c0_location), c0_gps)));
c0_aPhone.addConstraint(or(some(join(join(join(join($this(), c0_hardware), c0_screen), c0_material), c0_amoled)), some(join(join($this(), c0_hardware), c0_keyboard))));
c0_aPhone.addConstraint(or(or(some(join(join($this(), c0_software), c0_browser)), some(join(join($this(), c0_software), c0_map))), some(join(join($this(), c0_software), c0_mediaplayer))));
min(joinRef(join(global(c0_aPhone), c0_total_cost)));
